version: '3.8'

services:
  vue-app:
    build: .
    container_name: vue_app
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: yarn dev --host
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: backend_sqlite
    ports:
      - '3000:3000'
    volumes:
      - ./backend/players.db:/app/players.db
    environment:
      - NODE_ENV=production
    command: node server.js
